services:
  llama-server:
    build: .
    command: /llama/server --port 9000 -ngl 1000 -m /models/7B/wizardLM-7B.ggmlv3.q4_1.bin
    network_mode: host
    ports:
      - "9000:9000"
    volumes:
      - /mnt/data/ai/models:/models:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
